cp -v /opt/epics/opi/opi_BMM/MC01/opi_MC/*.edl opi_BMM/MC01/opi_MC/
cp -v /opt/epics/opi/opi_BMM/MC01/opi_MC/*.sh  opi_BMM/MC01/opi_MC/
cp -v /opt/epics/opi/opi_BMM/MC02/opi_MC/*.edl opi_BMM/MC02/opi_MC/
cp -v /opt/epics/opi/opi_BMM/MC02/opi_MC/*.sh  opi_BMM/MC02/opi_MC/
cp -v /opt/epics/opi/opi_BMM/MC03/opi_MC/*.edl opi_BMM/MC03/opi_MC/
cp -v /opt/epics/opi/opi_BMM/MC03/opi_MC/*.sh  opi_BMM/MC03/opi_MC/
cp -v /opt/epics/opi/opi_BMM/MC04/opi_MC/*.edl opi_BMM/MC04/opi_MC/
cp -v /opt/epics/opi/opi_BMM/MC04/opi_MC/*.sh  opi_BMM/MC04/opi_MC/
cp -v /opt/epics/opi/opi_BMM/MC05/opi_MC/*.edl opi_BMM/MC05/opi_MC/
cp -v /opt/epics/opi/opi_BMM/MC05/opi_MC/*.sh  opi_BMM/MC05/opi_MC/
cp -v /opt/epics/opi/opi_BMM/MC06/opi_MC/*.edl opi_BMM/MC06/opi_MC/
cp -v /opt/epics/opi/opi_BMM/MC06/opi_MC/*.sh  opi_BMM/MC06/opi_MC/
