#!/usr/bin/python

import sys
import os
import signal
import epics
from time import sleep
from termcolor import colored
#sys.path.append('/home/xf06bm/python')
from BMMcontrols import Mirror
import datetime, time
from numpy import pi, sin, cos, arcsin, deg2rad
HBARC = 1973.27053324

def writeline(string):
    sys.stdout.write('\r')
    sys.stdout.flush()
    sys.stdout.write(string)
    sys.stdout.flush()

def signal_handler(sig, frame):
    print('\nQuitting cadashboard. Bye.')
    sys.exit(0)  
signal.signal(signal.SIGINT, signal_handler)

## ----- various PVs and other scalars
i0           = epics.PV('XF:06BM-BI{EM:1}EM180:Current1:MeanValue_RBV')
it           = epics.PV('XF:06BM-BI{EM:1}EM180:Current2:MeanValue_RBV')
bicron       = epics.PV('XF:06BM-ES:1{Sclr:1}.S25')
ring_current = epics.PV('SR:OPS-BI{DCCT:1}I:Real-I')
sha          = epics.PV('XF:06BM-PPS{Sh:FE}Pos-Sts')
shb          = epics.PV('XF:06BM-PPS{Sh:A}Pos-Sts')
bragg        = epics.PV('XF:06BMA-OP{Mono:DCM1-Ax:Bragg}Mtr.RBV')
dcmx         = epics.PV('XF:06BMA-OP{Mono:DCM1-Ax:X}Mtr.RBV')
m2           = Mirror(2)

execfile('/home/xf06bm/.ipython/profile_collection/startup/19-dcm-parameters.py')

pattern = "%Y-%m-%dT%H-%M-%S"
strut = u'\u25CF'  # u'\u2589'

print('\n')
waiting = True
while waiting:

    xrd = False
    if m2.vert < 0 and m2.pitch > 3:
        xrd = True
    
    ## ----- shutters and ring current
    if sha.get() == 1:
        sha_show = colored('A shutter', 'red', attrs=['bold'])
    else:
        sha_show = colored('A shutter', 'green', attrs=['bold'])
        
    if shb.get() == 1:
        shb_show = colored('B shutter', 'red', attrs=['bold'])
    else:
        shb_show = colored('B shutter', 'green', attrs=['bold'])

    try:
        if ring_current.get() > 100:
            ring_show = colored('%5.1f mA' % ring_current.get(), 'cyan', attrs=None)
        else:
            ring_show = colored('%5.1f mA' % ring_current.get(), 'red', attrs=None)
    except:
            ring_show = colored('--------', 'red', attrs=None)

    ## ----- ion chamber signals
    i0val = 0
    try:
        i0val = i0.get()*10**9
    except:
        pass
    itval = 0
    try:
        itval = it.get()*10**9
    except:
        pass
    
    ## ----- current time for time updates
    now  = datetime.datetime.now().strftime("%s")
    left = '                            '
    scan =     colored('  idle    ', 'grey', 'on_white')
    if xrd:
        scan = colored('not in use', 'grey', 'on_white')
    
    ## ----- this is an XAFS scan
    if os.path.isfile('/home/xf06bm/Data/.xafs.scan.running'):
        #try:
        with open('/home/xf06bm/Data/.xafs.scan.running', "r") as f:
            start = float(f.readline())
            estimate = f.readline()
        elapsed = float(now) - start
        remaining = float(estimate[:-1]) - elapsed   # seconds
        if remaining < 0: remaining = 0
        hours = int(remaining/60./60.)
        minutes = round((remaining - hours*60*60) / 60)
        left = ' ~ %d h, %d m remaining  ' % (hours, minutes)
        #except:
        #    pass
        scan = colored('xafs scan ', 'grey', 'on_magenta')

    ## ----- this is a line scan
    elif os.path.isfile('/home/xf06bm/Data/.line.scan.running'):
        scan = colored('line scan ', 'grey', 'on_cyan')

    ## ----- this is an area scan
    elif os.path.isfile('/home/xf06bm/Data/.area.scan.running'):
        #try:
        with open('/home/xf06bm/Data/.area.scan.running', "r") as f:
            start = float(f.readline())
            estimate = f.readline()
        elapsed = float(now) - start
        remaining = int(estimate[:-1]) - elapsed # seconds
        if remaining < 0: remaining = 0
        minutes = int(remaining/60.)
        seconds = round(remaining - minutes*60)
        left = ' ~ %d m, %d s remaining  ' % (minutes, seconds)
        #except:
        #    pass
        scan = colored('area scan ', 'grey', 'on_yellow')
        
    ## ----- this is a time scan
    elif os.path.isfile('/home/xf06bm/Data/.time.scan.running'):
        with open('/home/xf06bm/Data/.time.scan.running', "r") as f:
            start = float(f.readline())
        elapsed = float(now) - start
        minutes = int(elapsed/60.)
        seconds = round(elapsed - minutes*60)
        left = ' ~ %d m, %d s elapsed' % (minutes, seconds)
        scan = colored('time scan ', 'grey', 'on_blue', attrs=['bold'])

    ## ----- update the display
    if dcmx.get() < 10:
        current_energy = (2*pi*HBARC) / (2*BMM_dcm.dspacing_111*sin(deg2rad(bragg.get())))
    else:
        current_energy = (2*pi*HBARC) / (2*BMM_dcm.dspacing_311*sin(deg2rad(bragg.get())))
    if xrd:
        writeline("  [%s]  [%s] %s ring: %s %s APD: %6d counts %s mono: %.1f eV %s XAS station: %s %s" %
                  (sha_show, shb_show, strut, ring_show, strut, int(bicron.get()), strut, current_energy, strut, scan, left))
        sleep(1.0)
    else:
        writeline("  [%s]  [%s] %s ring: %s %s I0: %7.3f nA   It: %7.3f nA %s mono: %.1f eV %s XAS station: %s %s" %
                  (sha_show, shb_show, strut, ring_show, strut, i0val, itval, strut, current_energy, strut, scan, left))
        sleep(1.0)
